### ISSUE TITLE
Is this working

### ISSUE THREAD

**Issue by enhancd-ai** [zoonaka/esp-idf_rust_example_gatts#1]
Hi, I'm wondering if you got this working. 
I keep getting this error and cant figure out why.
|         ^^^^^^^^^ `esp_bt_controller_config_t` does not have this field

Are you having the same issue?

**Comment by enhancd-ai** [comment]
Have got in compiling with this get_bt_cfg() function.

For esp32c3:

`pub fn get_bt_cfg() -> esp_idf_sys::esp_bt_controller_config_t {
    esp_idf_sys::esp_bt_controller_config_t {
        controller_task_stack_size: esp_idf_sys::ESP_TASK_BT_CONTROLLER_STACK as u16,
        controller_task_prio: esp_idf_sys::ESP_TASK_BT_CONTROLLER_PRIO as u8,
        scan_duplicate_mode: esp_idf_sys::SCAN_DUPLICATE_MODE as u8,
        scan_duplicate_type: esp_idf_sys::SCAN_DUPLICATE_TYPE_VALUE as u8,
        normal_adv_size: esp_idf_sys::NORMAL_SCAN_DUPLICATE_CACHE_SIZE as u16,
        mesh_adv_size: esp_idf_sys::MESH_DUPLICATE_SCAN_CACHE_SIZE as u16,
        // magic: 1515890085,
        magic: esp_idf_sys::ESP_BT_CTRL_CONFIG_MAGIC_VAL,
        version: esp_idf_sys::ESP_BT_CTRL_CONFIG_VERSION as u32,
        controller_task_run_cpu: esp_idf_sys::CONFIG_BT_CTRL_PINNED_TO_CORE as u8,
        bluetooth_mode: esp_idf_sys::CONFIG_BT_CTRL_MODE_EFF as u8,
        ble_max_act: esp_idf_sys::CONFIG_BT_CTRL_BLE_MAX_ACT_EFF as u8,
        sleep_mode: esp_idf_sys::CONFIG_BT_CTRL_SLEEP_MODE_EFF as u8,
        sleep_clock: esp_idf_sys::CONFIG_BT_CTRL_SLEEP_CLOCK_EFF as u8,
        ble_st_acl_tx_buf_nb: esp_idf_sys::CONFIG_BT_CTRL_BLE_STATIC_ACL_TX_BUF_NB as u8,
        ble_hw_cca_check: esp_idf_sys::CONFIG_BT_CTRL_HW_CCA_EFF as u8,
        ble_adv_dup_filt_max: esp_idf_sys::CONFIG_BT_CTRL_ADV_DUP_FILT_MAX as u16,
        coex_param_en: false,
        ce_len_type: esp_idf_sys::CONFIG_BT_CTRL_CE_LENGTH_TYPE_EFF as u8,
        coex_use_hooks: false,
        hci_tl_type: esp_idf_sys::CONFIG_BT_CTRL_HCI_TL_EFF as u8,
        hci_tl_funcs: &mut esp_idf_sys::esp_bt_hci_tl_t{
             _magic: esp_idf_sys::ESP_BT_CTRL_CONFIG_MAGIC_VAL,
             _version: 0,
             _reserved: 0,
             _open: None,
            _close: None,
            _finish_transfers: None,
            _recv: None,
            _send: None,
            _flow_off: None,
            _flow_on: None,  
        },
        txant_dft: esp_idf_sys::CONFIG_BT_CTRL_TX_ANTENNA_INDEX_EFF as u8,
        rxant_dft: esp_idf_sys::CONFIG_BT_CTRL_RX_ANTENNA_INDEX_EFF as u8,
        txpwr_dft: esp_idf_sys::CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_EFF as u8,
        cfg_mask: esp_idf_sys::CFG_NASK as u32,
        coex_phy_coded_tx_rx_time_limit: esp_idf_sys::CONFIG_BT_CTRL_COEX_PHY_CODED_TX_RX_TLIM_EFF as u8,
        hw_target_code: esp_idf_sys::BLE_HW_TARGET_CODE_ESP32C3_CHIP_ECO0 as u32,
        slave_ce_len_min: esp_idf_sys::SLAVE_CE_LEN_MIN_DEFAULT as u8,
        hw_recorrect_en: esp_idf_sys::AGC_RECORRECT_EN as u8,
        cca_thresh: esp_idf_sys::CONFIG_BT_CTRL_HW_CCA_VAL as u8,
    }
}`

**Comment by pRizz** [comment]
For posterity, here is an updated fn:

```rust
pub fn get_bt_cfg() -> esp_idf_sys::esp_bt_controller_config_t {
    esp_idf_sys::esp_bt_controller_config_t {
        controller_task_stack_size: esp_idf_sys::ESP_TASK_BT_CONTROLLER_STACK as u16,
        controller_task_prio: esp_idf_sys::ESP_TASK_BT_CONTROLLER_PRIO as u8,
        scan_duplicate_mode: esp_idf_sys::SCAN_DUPLICATE_MODE as u8,
        scan_duplicate_type: esp_idf_sys::SCAN_DUPLICATE_TYPE_VALUE as u8,
        normal_adv_size: esp_idf_sys::NORMAL_SCAN_DUPLICATE_CACHE_SIZE as u16,
        mesh_adv_size: esp_idf_sys::MESH_DUPLICATE_SCAN_CACHE_SIZE as u16,
        magic: esp_idf_sys::ESP_BT_CTRL_CONFIG_MAGIC_VAL,
        version: esp_idf_sys::ESP_BT_CTRL_CONFIG_VERSION as u32,
        controller_task_run_cpu: esp_idf_sys::CONFIG_BT_CTRL_PINNED_TO_CORE as u8,
        bluetooth_mode: esp_idf_sys::CONFIG_BT_CTRL_MODE_EFF as u8,
        ble_max_act: esp_idf_sys::CONFIG_BT_CTRL_BLE_MAX_ACT_EFF as u8,
        sleep_mode: esp_idf_sys::CONFIG_BT_CTRL_SLEEP_MODE_EFF as u8,
        sleep_clock: esp_idf_sys::CONFIG_BT_CTRL_SLEEP_CLOCK_EFF as u8,
        ble_st_acl_tx_buf_nb: esp_idf_sys::CONFIG_BT_CTRL_BLE_STATIC_ACL_TX_BUF_NB as u8,
        ble_hw_cca_check: esp_idf_sys::CONFIG_BT_CTRL_HW_CCA_EFF as u8,
        ble_adv_dup_filt_max: esp_idf_sys::CONFIG_BT_CTRL_ADV_DUP_FILT_MAX as u16,
        coex_param_en: false,
        ce_len_type: esp_idf_sys::CONFIG_BT_CTRL_CE_LENGTH_TYPE_EFF as u8,
        coex_use_hooks: false,
        hci_tl_type: esp_idf_sys::CONFIG_BT_CTRL_HCI_TL_EFF as u8,
        hci_tl_funcs: &mut esp_idf_sys::esp_bt_hci_tl_t {
            _magic: esp_idf_sys::ESP_BT_CTRL_CONFIG_MAGIC_VAL,
            _version: 0,
            _reserved: 0,
            _open: None,
            _close: None,
            _finish_transfers: None,
            _recv: None,
            _send: None,
            _flow_off: None,
            _flow_on: None,
        },
        txant_dft: esp_idf_sys::CONFIG_BT_CTRL_TX_ANTENNA_INDEX_EFF as u8,
        rxant_dft: esp_idf_sys::CONFIG_BT_CTRL_RX_ANTENNA_INDEX_EFF as u8,
        txpwr_dft: esp_idf_sys::CONFIG_BT_CTRL_DFT_TX_POWER_LEVEL_EFF as u8,
        cfg_mask: esp_idf_sys::CFG_MASK as u32,
        coex_phy_coded_tx_rx_time_limit: esp_idf_sys::CONFIG_BT_CTRL_COEX_PHY_CODED_TX_RX_TLIM_EFF
            as u8,
        hw_target_code: esp_idf_sys::BLE_HW_TARGET_CODE_CHIP_ECO0 as u32,
        slave_ce_len_min: esp_idf_sys::SLAVE_CE_LEN_MIN_DEFAULT as u8,
        hw_recorrect_en: esp_idf_sys::AGC_RECORRECT_EN as u8,
        cca_thresh: esp_idf_sys::CONFIG_BT_CTRL_HW_CCA_VAL as u8,
        // Unspecified
        scan_backoff_upperlimitmax: 0,
        dup_list_refresh_period: 0,
        ble_50_feat_supp: false,
        ble_cca_mode: 0,
        ble_data_lenth_zero_aux: 0,
        ble_chan_ass_en: 0,
        ble_ping_en: 0,
        ble_llcp_disc_flag: 0,
        run_in_flash: false,
        dtm_en: false,
        enc_en: false,
        qa_test: false,
        master_en: false,
        scan_en: false,
        ble_aa_check: false,
        ble_log_mode_en: 0,
        ble_log_level: 0,
    }
}
```
